AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with user data

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-057b6e529186a8233 # Specify your desired AMI ID here
      KeyName: demo-key       # Specify your key pair name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Welcome!</h1></body></html>" > /var/www/html/index.html
